language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
cache: pip
install:
  - pip3 install -r requirements.txt 
script:
  - pylint sunportal.py util --disable=R,C
  - python -m test.tests

