---
database:
  path: "./SBFspot.db"
co2_avoidance_factor: 0.7
mail:
  enabled: 'false'
  check_interval: 300
  sender: sunportal@example.com
  smtp_server:
    url: smtp.example.com
    port: 587
  recipients:
  - me@example.com
  starttls:
    enabled: 'false'
    user: ''
    password: ''
renaming:
  '2000079685': Inverter 1
  '2000098450': Inverter 2
  '2000099075': Inverter 3
  '2130309491': Inverter 4
  '2130340030': Inverter 5

